name: Build Keychron Keyboards

permissions:
  contents: read

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container: ghcr.io/qmk/qmk_cli
    
    strategy:
      matrix:
        include:
          - keyboard: keychron/k2_pro/ansi/rgb
            name: k2_pro_ansi_rgb
          - keyboard: keychron/k3_pro/ansi/rgb
            name: k3_pro_ansi_rgb
          - keyboard: keychron/q8_pro/ansi_encoder
            name: q8_pro_ansi_encoder
    
    steps:
      - name: Disable safe.directory check
        run: git config --global --add safe.directory '*'
      
      - name: Checkout QMK Firmware
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build firmware
        run: qmk compile -kb ${{ matrix.keyboard }} -km via
      
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.name }}
          path: |
            .build/*.bin
            .build/*.hex
            .build/*.uf2
          if-no-files-found: error
